version: '3.8'

services:
  flask:
    build: ./flask-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sampledb
    depends_on:
      - db
    volumes:
      - ./flask-app:/app
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sampledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: